Install Dependencies:
  stage: .pre
  image: trion/ng-cli:19.2.9
  cache: &cache
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules
    policy: pull-push
  script:
    npm install

Lint:
  image: trion/ng-cli:19.2.9
  cache:
    <<: *cache
    policy: pull
  script:
    - npm run lint

Test Karma:
  image: trion/ng-cli-karma:19.2.9
  cache:
    <<: *cache
    policy: pull
  script:
    - npm run test:ci

Test Build:
  image: trion/ng-cli:19.2.9
  cache:
    <<: *cache
    policy: pull
  script:
    - npm run build:library

Test Cypress:
  image: cypress/base:22.15.0
  cache:
    <<: *cache
    policy: pull
  before_script:
    - npm install
    - npx cypress install
  script:
    - npm run cypress:run-component
  after_script:
    - npm run cypress:print-coverage
    - npm run cypress:cobertura
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml


Build:
  image: trion/ng-cli:19.2.9
  cache:
    <<: *cache
    policy: pull
  script:
    - npm run build:library
  needs:
    - job: Lint
      artifacts: false
    - job: Test Build
      artifacts: false
    - job: Test Karma
      artifacts: false
    - job: Test Cypress
      artifacts: false
  artifacts:
    paths:
      - dist/form-signals
    expire_in: 1 week

Publish:
  image: trion/ng-cli:19.2.9
  needs:
    - job: Build
      artifacts: true
  when: manual
  before_script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
  script:
    - cd dist/form-signals
    - npm publish --access public
